codecov:
  require_ci_to_pass: true
coverage:
  status:
    patch: false
    project:
      default: false
      e2e-tests:
        flags:
        - e2e-tests
        threshold: 0.2%
      unit-tests:
        flags:
        - unit-tests
        threshold: 0.2%
flags:
  e2e-tests:
    carryforward: true
  unit-tests:
    carryforward: true
