## Validate this file before pushing by running this command from project the .github directory: 
## curl -X POST --data-binary @codecov.yml https://codecov.io/validate

component_management:
  individual_components:
    - component_id: admin_full_ember_app
      name: Admin
      paths:
        - ghost/admin/**
    - component_id: admin_publishing_flow
      name: Admin Publishing Flow
      paths:
        - ghost/admin/app/components/editor/publish-options/**
        - ghost/admin/app/components/editor/publish-management.js
        - ghost/admin/app/components/editor/publish-management.hbs
        - ghost/admin/app/components/editor/modals/publish-flow/**
        - ghost/admin/app/components/editor/modals/publish-flow.js
        - ghost/admin/app/components/editor/modals/publish-flow.hbs
    - component_id: site_setup_flow
      name: New Site Setup Flow
      paths:
        - ghost/admin/app/controllers/setup.js
        - ghost/admin/app/controllers/setup/done.js
    - component_id: email_service
      name: Email Service
      paths:
        - ghost/email-service/**
      statuses:           # the core component has its own statuses
        - type: project
          target: 100%
        - type: patch
          target: 100%
comment:
  behavior: default
  layout: diff,flags,components,tree
  show_carryforward_flags: false