dist: xenial
language: node_js
# When changing node version also update it on line 21
node_js:
  - "10"
  - "8"
  - "6"

cache: yarn

services:
  - mysql

env:
  matrix:
    - DB=sqlite3 NODE_ENV=testing
    - DB=mysql NODE_ENV=testing-mysql

matrix:
  include:
    - node_js: "10"
      env: TEST_SUITE=lint
  fast_finish: true

branches:
  except:
    - /^renovate\/.+$/

install:
  - yarn

before_script:
  - if [ $DB == "mysql" ]; then mysql -e 'create database ghost_testing'; fi
  - if [ "$DB" == "sqlite3" ]; then yarn add --force sqlite3; fi # fix sqlite caching issues

script: |
  if [ "$TEST_SUITE" == "lint" ]; then
    yarn lint
  elif [[ "$TRAVIS_PULL_REQUEST_BRANCH" =~ ^renovate || "$TRAVIS_EVENT_TYPE" == "cron" ]]; then
    yarn ci:regression
  else
    yarn ci
  fi

notifications:
  slack:
    secure: iqURdUniayDtpj8twQIUi027jkFDMfoqyYv6rmmF7Nb1Y+XoLeQbUNv1EQEoGG+N7n9FnRXQe6TawyjCk+6qBQJoEI2O4xSpvtnC81nnX5EKbNVgT+tfBXH/bUaLtgY3Z3NfoeCmwR3fK3wOhgN9m3Il5YgXx7KJFAXxjnYrKUo=
    on_success: change
    on_failure: always
    on_pull_requests: false
