language: node_js
# When changing node version also update it on lines 23 and 52.
node_js:
  - "10"
  - "8"
  - "6"

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    - GITHUB_OAUTH_KEY=003a44d58f12089d0c0261338298af3813330949
  matrix:
    - DB=sqlite3 NODE_ENV=testing
    - DB=mysql NODE_ENV=testing-mysql

matrix:
  include:
    - node_js: "10"
      env: TEST_SUITE=lint
  fast_finish: true

branches:
  except:
    - /^renovate\/.+$/

before_install:
  - if [ $DB == "mysql" ]; then mysql -e 'create database ghost_testing'; fi
  - curl -sSL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo -E apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee -a /etc/apt/sources.list >/dev/null
  - sudo -E apt-get -yq update &>> ~/apt-get-update.log
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends $TRAVIS_APT_OPTS install yarn

install:
  - yarn
  - if [ "$DB" == "sqlite3" ]; then yarn add --force sqlite3; fi # fix sqlite caching issues

script: |
  if [ "$TEST_SUITE" == "lint" ]
    yarn lint
  elif [[ "$TRAVIS_PULL_REQUEST_BRANCH" =~ ^renovate || "$TRAVIS_EVENT_TYPE" == "cron" ]]; then
    yarn ci:regression
  else
    yarn ci
  fi

notifications:
  slack:
    secure: iqURdUniayDtpj8twQIUi027jkFDMfoqyYv6rmmF7Nb1Y+XoLeQbUNv1EQEoGG+N7n9FnRXQe6TawyjCk+6qBQJoEI2O4xSpvtnC81nnX5EKbNVgT+tfBXH/bUaLtgY3Z3NfoeCmwR3fK3wOhgN9m3Il5YgXx7KJFAXxjnYrKUo=
    on_success: change
    on_failure: always
    on_pull_requests: false
