dist: xenial
language: node_js
node_js:
- '12'
- '10'
cache: yarn
services:
- mysql
branches:
  only:
    - master
    - 2.x
env:
  matrix:
  - DB=sqlite3 NODE_ENV=testing
  - DB=mysql NODE_ENV=testing-mysql
install:
- yarn
before_script:
- if [ $DB == "mysql" ]; then mysql -e 'create database ghost_testing'; fi
- if [ "$DB" == "sqlite3" ]; then yarn add --force sqlite3; fi
script: |
  if [[ "$TRAVIS_PULL_REQUEST_BRANCH" =~ ^renovate || "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    grunt test-all --verbose
  else
    yarn ci
  fi
