pygments:     true
permalinks: pretty
relative_permalinks: false
exclude:     ['node_modules', 'core', 'content']
markdown: redcarpet
languages:
    - name: 'English'
      key: 'en'
    - name: '中文'
      key: 'zh'
    - name: '한국의'
      key: 'ko'
    - name: 'Deutsch'
      key: 'de'
    - name: 'Français'
      key: 'fr'
    - name: 'Polski'
      key: 'pl'
    - name: '日本語'
      key: 'ja'
    - name: 'Italiano'
      key: 'it'

port:         4478

translations:
  zh:
    site_title:   'Ghost使用指南'
    installation: '安装'
    usage:        '使用'
    email:        '邮件'
    themes:       '主题'
    translations: '翻译'
    help:         '帮助'
    ghost-hosted-platform: 'Ghost Hosted Platform'
  ko:
    site_title:   'Ghost Guide'
    installation: 'Installation'
    usage:        'Usage'
    email:        'Email'
    themes:       'Themes'
    translations: 'Translations'
    help:         'Help'
    ghost-hosted-platform: 'Ghost Hosted Platform'
  de:
    site_title:   'Ghost-Handbuch'
    installation: 'Installation'
    usage:        'Anwendung'
    email:        'E-Mail'
    themes:       'Themen'
    help:         'Hilfe'
    deploy:       'Einsetzen'
    upgrading:    'Aktualisieren' 
    troubleshooting: 'Problembehebung'
    ghost-hosted-platform: 'Ghost Hosted Platform'
  fr:
    site_title:   'Guide Ghost'
    installation: 'Installation'
    usage:        'Usage'
    email:        'Email'
    themes:       'Thèmes'
    translations: 'Traductions'
    help:         'Aide'
    ghost-hosted-platform: 'Ghost Hosted Platform'
  pl:
    site_title:   'Ghost Guide'
    installation: 'Installation'
    usage:        'Usage'
    email:        'Email'
    themes:       'Themes'
    translations: 'Translations'
    help:         'Help'
    ghost-hosted-platform: 'Ghost Hosted Platform'
  ja:
    site_title:   'Ghost日本語ガイド'
    installation: 'インストール'
    usage:        '使い方'
    email:        'メール設定'
    themes:       'テーマ'
    help:         'ヘルプ'
    deploy:       'デプロイ'
    upgrading:    'アップグレード'
    troubleshooting: 'トラブルシューティング'
    configuration: '高度な設定'
    settings:     'ブログの設定'
    managing:     '記事の管理'
    writing:      '記事を書く'
    faq:          'Q&A'
    ghost-hosted-platform: 'Ghost Hosted Platform'
  it:
    site_title:   'Guida a Ghost'
    installation: 'Installazione'
    usage:        'Utilizzo'
    email:        'Email'
    themes:       'Temi'
    translations: 'Traduzioni'
    help:         'Aiuto'
    deploy:       'Deploy'
    upgrading:    'Aggiornamento' 
    troubleshooting: 'Risoluzione dei Problemi'
    ghost-hosted-platform: 'Ghost Hosted Platform'

# If running locally, simply comment out the line below to make all urls relative

#url:          http://docs.ghost.org
