pygments:     true
permalinks: pretty
relative_permalinks: false
markdown: redcarpet
languages:
    - name: 'English'
      key: 'en'
    - name: '中文'
      key: 'zh'
    - name: '한국의'
      key: 'ko'
<<<<<<< HEAD
<<<<<<< HEAD
    - name: 'Danish'
      key: 'da'
=======
    - name: 'Français'
      key: 'fr'
>>>>>>> Update config to add french
=======
    - name: 'Deutsch'
      key: 'de'
    - name: 'Français'
      key: 'fr'

>>>>>>> Started German translation
port:         4478

translations:
  zh:
    site_title:   'Ghost使用指南'
    installation: '安装'
    usage:        '使用'
    email:        '邮件'
    themes:       '主题'
    translations: '翻译'
    help:         '帮助'
  ko:
    site_title:   'Ghost Guide'
    installation: 'Installation'
    usage:        'Usage'
    email:        'Email'
    themes:       'Themes'
    translations: 'Translations'
    help:         'Help'
<<<<<<< HEAD
<<<<<<< HEAD
  da:
    site_title:   'Ghost guide'
    installation: 'Installation'
    usage:        'Brug'
    email:        'E-mail'
    themes:       'Temaer'
    translations: 'Oversættelser'
    help:         'Hjælp'
=======
=======
  de:
    site_title:   'Ghost-Handbuch'
    installation: 'Installation'
    usage:        'Anwendung'
    email:        'E-Mail'
    themes:       'Themen'
    help:         'Hilfe'
<<<<<<< HEAD
>>>>>>> Started German translation
=======
    deploy:       'Einsetzen'
    upgrading:    'Aktualisieren' 
    troubleshooting: 'Problembehebung'
>>>>>>> Translate Installation & Mail to German and apply updates
  fr:
    site_title:   'Guide Ghost'
    installation: 'Installation'
    usage:        'Usage'
    email:        'Email'
    themes:       'Thèmes'
    translations: 'Traductions'
    help:         'Aide'
>>>>>>> Update config to add french

# If running locally, simply comment out the line below to make all urls relative

#url:          http://docs.ghost.org
