pygments:     true
permalinks: pretty
relative_permalinks: false
markdown: redcarpet
languages:
    - name: 'English'
      key: 'en'
    - name: '中文'
      key: 'zh'
    - name: '한국의'
      key: 'ko'
    - name: 'Español'
      key: 'es'
port:         4478

translations:
  zh:
    site_title:   'Ghost使用指南'
    installation: '安装'
    usage:        '使用'
    email:        '邮件'
    themes:       '主题'
    translations: '翻译'
    help:         '帮助'
  ko:
    site_title:   'Ghost Guide'
    installation: 'Installation'
    usage:        'Usage'
    email:        'Email'
    themes:       'Themes'
    translations: 'Translations'
    help:         'Help'
  es:
    site_title:   'Guía Ghost'
    installation: 'Instalación'
    usage:        'Uso'
    email:        'Email'
    themes:       'Temas'
    translations: 'Traducciones'
    help:         'Ayuda' 
# If running locally, simply comment out the line below to make all urls relative

#url:          http://docs.ghost.org
