pygments:     true
permalinks: pretty
relative_permalinks: false
markdown: redcarpet
languages:
    - name: 'English'
      key: 'en'
    - name: '中文'
      key: 'zh'
    - name: '한국의'
      key: 'ko'
    - name: 'Danish'
      key: 'da'
port:         4478

translations:
  zh:
    site_title:   'Ghost使用指南'
    installation: '安装'
    usage:        '使用'
    email:        '邮件'
    themes:       '主题'
    translations: '翻译'
    help:         '帮助'
  ko:
    site_title:   'Ghost Guide'
    installation: 'Installation'
    usage:        'Usage'
    email:        'Email'
    themes:       'Themes'
    translations: 'Translations'
    help:         'Help'
  da:
    site_title:   'Ghost guide'
    installation: 'Installation'
    usage:        'Brug'
    email:        'E-mail'
    themes:       'Temaer'
    translations: 'Oversættelser'
    help:         'Hjælp'

# If running locally, simply comment out the line below to make all urls relative

#url:          http://docs.ghost.org