pygments:     true
permalinks: pretty
relative_permalinks: false
markdown: redcarpet
languages:
    - name: 'English'
      key: 'en'
    - name: '中文'
      key: 'zh'
    - name: '한국의'
      key: 'ko'
    - name: 'Deutsch'
      key: 'de'
    - name: 'Français'
      key: 'fr'
    - name: 'Polski'
      key: 'pl'
    - name: '日本語'
      key: 'ja'

port:         4478

translations:
  zh:
    site_title:   'Ghost使用指南'
    installation: '安装'
    usage:        '使用'
    email:        '邮件'
    themes:       '主题'
    translations: '翻译'
    help:         '帮助'
  ko:
    site_title:   'Ghost Guide'
    installation: 'Installation'
    usage:        'Usage'
    email:        'Email'
    themes:       'Themes'
    translations: 'Translations'
    help:         'Help'
  de:
    site_title:   'Ghost-Handbuch'
    installation: 'Installation'
    usage:        'Anwendung'
    email:        'E-Mail'
    themes:       'Themen'
    help:         'Hilfe'
    deploy:       'Einsetzen'
    upgrading:    'Aktualisieren' 
    troubleshooting: 'Problembehebung'
  fr:
    site_title:   'Guide Ghost'
    installation: 'Installation'
    usage:        'Usage'
    email:        'Email'
    themes:       'Thèmes'
    translations: 'Traductions'
    help:         'Aide'
  pl:
    site_title:   'Ghost Guide'
    installation: 'Installation'
    usage:        'Usage'
    email:        'Email'
    themes:       'Themes'
    translations: 'Translations'
    help:         'Help'
  ja:
    site_title:   'Ghost日本語ガイド'
    installation: 'インストール'
    usage:        '使い方'
    email:        'メール設定'
    themes:       'テーマ'
    help:         'ヘルプ'
    deploy:       'デプロイ'
    upgrading:    'アップグレード'
    troubleshooting: 'トラブルシューティング'
    configuration: '高度な設定'
    settings:     'ブログの設定'
    managing:     '記事の管理'
    writing:      '記事を書く'
    faq:          'Q&A'

# If running locally, simply comment out the line below to make all urls relative

#url:          http://docs.ghost.org
