pygments:     true
permalinks: pretty
relative_permalinks: false
markdown: redcarpet
languages:
    - name: 'English'
      key: 'en'
    - name: '中文'
      key: 'zh'
    - name: '한국의'
      key: 'ko'
    - name: 'Deutsch'
      key: 'de'
    - name: 'Français'
      key: 'fr'
    - name: 'Polski'
      key: 'pl'
    - name: '日本語'
      key: 'ja'
    - name: 'Italiano'
      key: 'it'
    - name: '繁體中文'
      key: 'zh_TW'
    - name: 'Nederlands'
      key: 'nl_NL'

port:         4478

translations:
  zh:
    site_title:   'Ghost使用指南'
    installation: '安装'
    usage:        '使用'
    email:        '邮件'
    themes:       '主题'
    translations: '翻译'
    help:         '帮助'
    deploy:       '部署'
    upgrading:    '升级'
    troubleshooting: '纠错 & 常见问题'
    configuration: '配置'
    faq:          'FAQ'
    managing:     '博客管理'
    settings:     '博客设置'
    writing:      '写作'
    back:         '上一章'
    next:         '下一章'
  ko:
    site_title:   'Ghost Guide'
    installation: 'Installation'
    usage:        'Usage'
    email:        'Email'
    themes:       'Themes'
    translations: 'Translations'
    help:         'Help'
  de:
    site_title:   'Ghost-Handbuch'
    installation: 'Installation'
    usage:        'Anwendung'
    email:        'E-Mail'
    themes:       'Themen'
    help:         'Hilfe'
    deploy:       'Einsetzen'
    upgrading:    'Aktualisieren' 
    troubleshooting: 'Problembehebung'
    configuration: 'Konfiguration'
    faq: 'FAQ'
    managing: 'Verwalten'
    settings: 'Einstellungen'
    writing: 'Schreiben'
  fr:
    site_title:   'Guide Ghost'
    installation: 'Installation'
    usage:        'Usage'
    email:        'Email'
    themes:       'Thèmes'
    translations: 'Traductions'
    help:         'Aide'
  pl:
    site_title:   'Ghost Guide'
    installation: 'Installation'
    usage:        'Usage'
    email:        'Email'
    themes:       'Themes'
    translations: 'Translations'
    help:         'Help'
  ja:
    site_title:   'Ghost日本語ガイド'
    installation: 'インストール'
    usage:        '使い方'
    email:        'メール設定'
    themes:       'テーマ'
    help:         'ヘルプ'
    deploy:       'デプロイ'
    upgrading:    'アップグレード'
    troubleshooting: 'トラブルシューティング'
    configuration: '高度な設定'
    settings:     'ブログの設定'
    managing:     '記事の管理'
    writing:      '記事を書く'
    faq:          'Q&A'
  it:
    site_title:   'Guida a Ghost'
    installation: 'Installazione'
    usage:        'Utilizzo'
    email:        'Email'
    themes:       'Temi'
    translations: 'Traduzioni'
    help:         'Aiuto'
    deploy:       'Deploy'
    upgrading:    'Aggiornamento' 
    troubleshooting: 'Risoluzione dei Problemi'
  zh_TW:
    site_title:   'Ghost 使用手冊'
    installation: '安裝'
    usage:        '使用說明'
    email:        '電子郵件'
    themes:       '佈景主題'
    translations: '翻譯'
    help:         '說明'
  nl_NL:
    site_title:   'Ghost handleiding'
    installation: 'Installatie'
    usage:        'Gebruik'
    email:        'E-Mail'
    themes:       'Thema's'
    help:         'Help'
    deploy:       'Verspreiden'
    upgrading:    'Vernieuwen' 
    troubleshooting: 'Probleemoplossing'
    configuration: 'Configuratie'
    faq: 'FAQ'
    managing: 'Beheren'
    settings: 'Instellingen'
    writing: 'Schrijven'  

# If running locally, simply comment out the line below to make all urls relative

#url:          http://docs.ghost.org
