component_management:
  individual_components:
    - component_id: module_admin
      name: admin
      paths:
        - ghost/admin/**
comment:
  behavior: default
  layout: reach,diff,flags,components,tree,reach
  show_carryforward_flags: false