routes:

# '{globals.permalinks}' is the notation to access your configured permalink format from your blog's database.
collections:
  /:
    permalink: '{globals.permalinks}'
    template:
      - home
      - index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
