sudo: required
dist: trusty

language: node_js
node_js:
  - "10"

env:
  global:
    - MOZ_HEADLESS=1
    - JOBS=1 # See https://git.io/vdao3 for details.

branches:
  except:
    - /^renovate\//

cache:
  yarn: true

addons:
  firefox: "latest"
  chrome: "stable"

before_install:
  # install latest yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn

script:
  - npm run lint:js && COVERAGE=true npm test

after_success:
  - npm run coverage

after_failure: |
  if [ "${TRAVIS_EVENT_TYPE}" == "cron" ]; then
    curl -X POST --data-urlencode "payload={\"attachments\": [{\"color\": \"danger\", \"fallback\": \"Build Failure: $TRAVIS_JOB_WEB_URL\", \"title\": \"Build Failure\", \"text\": \"$TRAVIS_JOB_WEB_URL\"}]}" $SLACK_URL
  fi
