name: Browser Tests
on:
  workflow_dispatch:
    inputs:
      site_url:
        description: 'Site URL to test'
        required: true
        type: string
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ghost/core
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: yarn

    - name: Install dependencies
      run: yarn

    - name: Install Playwright
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: yarn test:browser
      env:
        TEST_URL: ${{ github.event.inputs.site_url }}

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
