name: Custom build
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build from'
        type: string
        required: false
        default: 'main'
      version:
        description: 'Version to build'
        type: string
        required: true
env:
  FORCE_COLOR: 1
jobs:
  custom:
    uses: tryghost/actions/.github/workflows/custom.yml@main
    with:
      branch: ${{ inputs.branch }}
      version: ${{ inputs.version }}
