name: 'Label Issues'

on:
  issues:
    types: [opened, closed, labeled]
  schedule:
    - cron:  '0 * * * *'

jobs:
  action:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'TryGhost'
    steps:
      - uses: tryghost/label-actions@main
