name: Release
on:
  push:
    tags:
      - '*'
jobs:
  automate:
    runs-on: ubuntu-18.04
    env:
      RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_NOTIFICATION_URL: ${{ secrets.RELEASE_NOTIFICATION_URL }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-node@v2
        env:
          FORCE_COLOR: 0
        with:
          node-version: '14'
          cache: yarn

      - run: yarn
      - run: grunt release --skip-tests
      - run: npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
      - run: npm publish
      - uses: tryghost/action-ghost-release@main
