name: Signup Form Tests
on:
  pull_request:
    paths:
      - 'ghost/signup-form/**'
  push:
    branches:
      - main
      - 'v5.*'
    paths:
      - 'ghost/signup-form/**'
env:
  FORCE_COLOR: 1
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  e2e:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))
    name: E2E
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        env:
          FORCE_COLOR: 0
        with:
          node-version: "18.12.1"
          cache: yarn

      - run: yarn --prefer-offline

      - name: Install Playwright
        run: npx playwright install --with-deps

      - run: yarn workspace @tryghost/signup-form run test:e2e

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 30

      - uses: tryghost/actions/actions/slack-build@main
        if: failure() && github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
